version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: developmentdb
      MYSQL_USER: developer
      MYSQL_PASSWORD: secret123
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
